### ISSUE TITLE
Cannot be activated in Symphony 2.6.11 (newest version)

### ISSUE THREAD

**Issue by afiller** [twiro/multilingual#16]
Hi,

when trying to install the extension in Symphony 2.6.11 I get an error 500. The Apache error log says:

`mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in /...[anonymized]..../httpdocs/extensions/multilingual/extension.driver.php on line 343, referer: https://.. [anonymized]...../admin/system/extensions/`

Any idea? Thanks in advance! :-)

**Comment by twiro** [comment]
Ah... that Bug must've been introduced by the latest update! I won't be able to fix this before (probably) monday but you could try to install [version 1.1.0](https://github.com/twiro/multilingual/tree/1.1.0) instead of 1.2.0 - that should work and you can update as soon as a new bugfix version will be released.

Which version of PHP are you using?

**Comment by afiller** [comment]
Thank you, 1.1.0 works!

The PHP version is the following:
PHP 5.3.10-1ubuntu3.26 with Suhosin-Patch (cli) (built: Feb 13 2017 20:37:51)

**Comment by twiro** [comment]
> _Thank you, 1.1.0 works!_

That's great - I just [submitted a **bugfix-branch (1.2.1)**](https://github.com/twiro/multilingual/tree/1.2.1) that should make the current version work with PHP 5.3. Could you give it a try? The oldest PHP version available to me right now is 5.4.

And if you find the time it would be very helpful if you could give the current [integration-branch](https://github.com/twiro/multilingual/tree/integration) a try too - I've added quite some new features over the last weeks and am planning to release version 2.0.0 soon, but only tested with PHP 5.5 and 5.6 yet. Would be good to know if it runs fine with PHP 5.3 too.

**Comment by twiro** [comment]
Ping @afiller !

The fix for PHP 5.3 has been released in the master-branch ([1.2.1](https://github.com/twiro/multilingual/releases/tag/1.2.1)) which now should support PHP 5.3-5.6 aswell as PHP 7.X.

Let me know if you run into any more troubles.
