### ISSUE TITLE
Doesn't work for associated items (Subsection Manager / Association Field)

### ISSUE THREAD

**Issue by mblabs** [twiro/multilingual#7]
When I fill a subsection manager field of an entry, the multilingual-item inserted in the SSM field isn't correctly processed by the front-end. I know I can create a third DS to solve the problem, but I ask if it's possible to have the correct parameters in the Principal DS

**Comment by twiro** [comment]
Subsection Manager won't be supported as it's been deprecated for a while now, but there is a working fix for association field ( https://github.com/twiro/multilingual/pull/11 ) that will be included in an upcoming 1.2 release in the next days.

**Comment by twiro** [comment]
Fixed in version 1.2.0 https://github.com/twiro/multilingual/tree/1.2.0
